sudo: false
language: python
cache:
  apt: true
  directories:
  - $HOME/.cache/pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - hash -r
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pyqt numpy scipy matplotlib
  - conda info -a
  - "pip install coveralls --upgrade"
  - "pip install coverage --upgrade"
  - "pip install pytest --upgrade"
  - "pip install pytest-runner --upgrade"
  - "pip install pytest-cov --upgrade"
  - "pip install pytest-logging --upgrade"
  - python configure.py
  - python setup.py develop
script: "py.test --cov=PyPWA tests/ -vvvv"
after_success:
  - ls -a
  - coveralls
  - head .coverage
notifications:
  emails:
    on_success: change
    on_failure: change
